ONE_SECOND = 1000

_TIME_TO_UNSTARVE_MS = 5000


LAST_ALIVE_STARVATION_LEVEL = 5
DEAD_STARVATION_LEVEL = 6

MIN_CPU_COUNT = 1
MAX_CPU_COUNT = 16
MIN_PROCESSES_AT_STARTUP = 1
MAX_PROCESSES_AT_STARTUP = 42
MIN_RAM_ROWS = 1
MAX_RAM_ROWS = 15

MAX_PAGES_PER_PROCESS = 4


MAX_PROCESSES = 42 +  MAX_CPU_COUNT -1